name: Add Reviewer on Command

on:
  issue_comment:
    types: [created]

jobs:
  add-reviewer:
    if: |
      github.event.issue.pull_request &&
      (
      contains(github.event.comment.body, '/mirrobot-add') ||
      contains(github.event.comment.body, '/mirrobot_add')
      )
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # To add a reviewer
      issues: write # To add a reaction

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Add mirrobot-agent as a reviewer
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh pr edit $PR_NUMBER --add-reviewer mirrobot-agent[bot] --repo ${{ github.repository }}

      - name: Add reaction to comment
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f content='eyes'